Added support for async fields
Q42/vue-dotnet-validator pull request #27
Opened 2021-03-02 14:26 UTC by basvanbovene

- Open example
- Wait for the async validator to appear after 2.5seconds
- Check if the required validator works

2021-03-02 15:24 UTC, RubenBimmel requested changes
De validator werkt nu niet als het veld aan het laden is. Ik weet niet of het alleen gekke testdata is, maar als ik in het voorbeeld alle andere velden weghaal kan ik gelijk submitten als het async veld nog niet geladen is.

2021-03-02 15:24 UTC, RubenBimmel commented on src/validator.js
> +              if (process.env.NODE_ENV !== 'production') {
Werkt dit ook bij andere projecten, of is dit een NLO setup? Ik snap niet helemaal waarom we niet gewoon altijd een warning / error willen tonen.

2021-03-02 15:24 UTC, RubenBimmel commented on src/validator.js
>        this.$nextTick(() => {
Deze `this.$nextTick()` is nu uit de mounted?

2021-03-03 08:20 UTC, basvanbovene commented on src/validator.js
>        this.$nextTick(() => {
Klopt want hij checkt nu iedere updatet of er velden voor validatie zijn. Daarmee is deze overbodig geworden.

2021-03-03 08:22 UTC, basvanbovene commented on src/validator.js
> +              if (process.env.NODE_ENV !== 'production') {
Als je een async form field hebt dan gaat hij die errors gooien op de mounted initialize. Dat vinden we in een productie omgeving niet zo netjes, maar wel behulpzaam in een dev omgeving.

@guidobouman kunnen we ervan uitgaan dat iedereen die de package gebruikt dit ook in de setup heeft?

2021-03-03 14:22 UTC, RubenBimmel requested changes

2021-03-03 14:22 UTC, RubenBimmel commented on src/validator.js
> +            console.warn('Tring to validate without a field');
Deze warning wordt nu nooit aangeroepen. Omdat het een computed property is kan deze na de mounted alleen veranderen als hij een veld krijgt.

We zouden hem eventueel in de `shoshowValidationMessage` kunnen zetten, omdat dat wel een method is. Maar anders deze er toch maar uit halen denk ik?

2021-03-03 14:31 UTC, basvanbovene commented on src/validator.js
> +            console.warn('Tring to validate without a field');
Daar heb je zeker een punt, ik heb hem naar de method verplaatst. 👍

2021-03-03 14:51 UTC, RubenBimmel approved these changes

2021-03-03 15:26 UTC, merged